test_shuffle (tests_1_random_.TestRandomFunctions) ... ok
test_sample (tests_1_random_.TestRandomFunctions) ... ok
test_choice (tests_1_random_.TestRandomFunctions) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.002s

OK
test_shuffle (tests_1_random_.TestRandomFunctions) ... ok
test_sample (tests_1_random_.TestRandomFunctions) ... FAIL
test_choice (tests_1_random_.TestRandomFunctions) ... ok

======================================================================
FAIL: test_sample (tests_1_random_.TestRandomFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\apps\testcase\bk_mobile\tests\tests_1_random_.py", line 52, in test_sample
    self.assertListEqual(self.seq, random.sample(self.seq, 5))
AssertionError: Lists differ: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] != [7, 8, 1, 4, 0]

First differing element 0:
0
7

First list contains 5 additional elements.
First extra element 5:
5

- [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
+ [7, 8, 1, 4, 0]

----------------------------------------------------------------------
Ran 3 tests in 0.007s

FAILED (failures=1)
test_shuffle (tests_1_random_.TestRandomFunctions) ... ok
test_sample (tests_1_random_.TestRandomFunctions) ... ok
test_choice (tests_1_random_.TestRandomFunctions) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.003s

OK
test_shuffle (tests_1_random_.TestRandomFunctions) ... ok
test_sample (tests_1_random_.TestRandomFunctions) ... ok
test_choice (tests_1_random_.TestRandomFunctions) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.004s

OK
test_shuffle (tests_1_random_.TestRandomFunctions) ... ok
test_sample (tests_1_random_.TestRandomFunctions) ... ok
test_choice (tests_1_random_.TestRandomFunctions) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.004s

OK
